language: php

php:
  - 5.4
  - 5.5

before_install:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install --prefer-source --dev --no-interaction
 - cd tests

script:
 - ../vendor/bin/phpunit
 - ../vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml --exclude-group Performance
 - ../vendor/bin/phpunit --group=Functional

after_script:
 - php vendor/bin/coveralls -v
